### PR TITLE
Build AppImage on Travis CI and upload to GitHub Releases

### PR DESCRIPTION
**Pull request by probonopd**
This PR, when merged, will compile this application on [Travis CI](https://travis-ci.org/) upon each `git push`, and upload an [AppImage](http://appimage.org/) to your GitHub Releases page.

Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/apps) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

__PLEASE NOTE:__ For this to work, you need to enable Travis CI for your repository as [described here](https://travis-ci.org/getting_started) __prior to merging this__, if you haven't already done so. Also, You need to set up `GITHUB_TOKEN` in Travis CI for this to work; please see https://github.com/probonopd/uploadtool.
If you would like to see only one entry for the Pull Request in your project's history, then please enable [this GitHub functionality](https://help.github.com/articles/configuring-commit-squashing-for-pull-requests/) on your repo. It allows you to squash (combine) the commits when merging.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

Reference:
https://github.com/abau/dilay/issues/39#issuecomment-372139601

### CODE REVIEW

**Comment by abau** [comment]
Thanks for your PR, but I'd rather create the image locally and upload it manually (as I do with the releases for Windows) than managing a CI. I'll use [.travis.yml](https://github.com/probonopd/dilay/blob/80ef30cd7e9ca78390844a3034e3e56c787aa099/.travis.yml) as a starting point for doing so.

**Comment by probonopd** [comment]
@abau may I ask why you prefer to do it manually? Travis CI, once set up, is pretty much zero-maintenance... and it helps in terms of others being able to reproduce your own builds. Buy hey, your decision ;-)

**Comment by abau** [comment]
Because the PR relies on two scripts fetched from a repository I don't have control over, thus, I'd rather run and check the Appimage build manually instead of uploading and releasing automatically from a CI.

**Comment by abau** [comment]
I just tried to build the appimage in a Docker container and ran into the [Fuse-not-available-in-Docker issue](https://github.com/AppImage/AppImageKit/wiki/FUSE#docker), which I think is also addressed in https://github.com/probonopd/linuxdeployqt/issues/107. How does this `--appimage-extract` flag work with `linuxdeployqt*.AppImage`?

**Comment by probonopd** [comment]
@TheAssassin is our Docker guru in residence, he certainly can explain what is going on here?

**Comment by TheAssassin** [comment]
@abau the link you posted explains it all. If you have problems in understanding it, please word a precise question that I could reply to.

**Comment by abau** [comment]
Sorry @TheAssassin, I must have missed your response. I got it working now. Thanks to both of you: next version of Dilay will have an AppImage!

**Pull request closed without merging**
